import {importBook} from './storage.js';
const api=globalThis.browser||globalThis.chrome;const button=document.querySelector('#open'),status=document.querySelector('#status');let url;
try{url=new URL(new URLSearchParams(location.search).get('url'));if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw new Error('Unsupported document address');document.querySelector('#origin').textContent=url.href;}catch(error){status.textContent=error.message;button.disabled=true;}
function permission(origin){return new Promise(resolve=>{if(globalThis.browser)api.permissions.request({origins:[origin]}).then(resolve,()=>resolve(false));else api.permissions.request({origins:[origin]},resolve);});}
button.onclick=async()=>{button.disabled=true;try{
 if(!await permission(url.origin+'/*'))throw new Error('Site access was not granted. Download the file yourself and add it to the shelf.');
 status.textContent='Downloading…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000);let response,parts=[],total=0;
 try{response=await fetch(url.href,{signal:controller.signal,credentials:'omit',redirect:'error'});if(!response.ok)throw new Error('HTTP '+response.status);if(+response.headers.get('content-length')>64*1048576)throw new Error('Maximum file size: 64 MiB');const reader=response.body.getReader();while(true){const {value,done}=await reader.read();if(done)break;total+=value.byteLength;if(total>64*1048576){await reader.cancel();throw new Error('Maximum file size: 64 MiB');}parts.push(value);}}finally{clearTimeout(timer);}
 const name=decodeURIComponent(url.pathname.split('/').pop())||'document.pdf';const file=new File(parts,name,{type:response.headers.get('content-type')||'application/octet-stream'});const {book}=await importBook(file);const viewer=new Sela({data:await file.arrayBuffer(),format:book.format,id:book.id,title:book.name,storagePrefix:'sela-library:',language:'auto',theme:'auto',soundEnabled:false});await viewer.open();status.textContent='Saved to your shelf.';
 }catch(error){status.textContent=error.message;button.disabled=false;}};
