import {test,expect} from '@playwright/test';
test('catalog requests are opt-in, safe records link to providers, and Gutenberg imports into the local shelf',async({page})=>{
 const requests=[];page.on('request',r=>{if(/openlibrary|gutendex|googleapis|microsoftonline/.test(r.url()))requests.push(r.url());});
 await page.route('https://gutendex.com/books/**',r=>r.fulfill({json:{results:[{id:123,title:'Quiet interval',authors:[{name:'A writer'}],copyright:false,formats:{'application/epub+zip':'https://www.gutenberg.org/ebooks/123.epub'}}]}}));
 await page.route('https://www.gutenberg.org/ebooks/123.epub',async r=>{const {readFile}=await import('node:fs/promises');await r.fulfill({body:await readFile('example/yang-tidak-ikut-pulang.epub')});});
 await page.route('https://openlibrary.org/search.json**',r=>r.fulfill({json:{docs:[{key:'/works/OL123W',title:'<script>safe title</script>',author_name:['Catalog author'],ebook_access:'borrowable'}]}}));
 await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');expect(requests).toEqual([]);
 await page.getByRole('button',{name:'Explore',exact:true}).click();await page.getByRole('button',{name:'Find open books',exact:true}).click();expect(requests).toEqual([]);
 const catalog=page.locator('.open-catalog');await catalog.getByLabel('Catalog').selectOption('gutenberg');await catalog.getByRole('button',{name:'Search',exact:true}).click();await expect(catalog.locator('.open-book')).toContainText('Quiet interval');
 await catalog.getByRole('button',{name:'Add to shelf',exact:true}).click();await page.getByRole('button',{name:'Shelf',exact:true}).click();await expect(page.locator('#shelf .book')).toHaveCount(1);
 await page.getByRole('button',{name:'Explore',exact:true}).click();await catalog.getByLabel('Catalog').selectOption('openlibrary');await page.waitForTimeout(1100);await catalog.getByRole('button',{name:'Search',exact:true}).click();await expect(catalog.locator('.open-book h4')).toHaveText('<script>safe title</script>');await expect(catalog.locator('script')).toHaveCount(0);await expect(catalog.getByRole('link',{name:'View on Open Library ↗'})).toHaveAttribute('href','https://openlibrary.org/works/OL123W');
});
test('cloud setup is explicit, Google SDK loads on demand, and only the selected file is imported',async({page})=>{
 const sdk=[];page.on('request',r=>{if(/apis.google.com|accounts.google.com/.test(r.url()))sdk.push(r.url());});
 await page.route('https://apis.google.com/js/api.js',r=>r.fulfill({contentType:'application/javascript',body:`window.gapi={load:(name,opts)=>opts.callback()};window.google=window.google||{};window.google.picker={Action:{CANCEL:'cancel',PICKED:'picked'},DocsView:class{setIncludeFolders(){return this}setSelectFolderEnabled(){return this}},PickerBuilder:class{addView(){return this}setOAuthToken(){return this}setDeveloperKey(){return this}setAppId(){return this}setOrigin(){return this}setCallback(cb){this.cb=cb;return this}build(){return this}setVisible(){this.cb({action:'picked',docs:[{id:'book-id',name:'Cloud book.txt',sizeBytes:12}]})}}};` }));
 await page.route('https://accounts.google.com/gsi/client',r=>r.fulfill({contentType:'application/javascript',body:`window.google=window.google||{};window.google.accounts={oauth2:{initTokenClient:opts=>({requestAccessToken:()=>{window.testScope=opts.scope;opts.callback({access_token:'test-access-token'})}})}};` }));
 await page.route('https://www.googleapis.com/drive/v3/files/book-id?alt=media',r=>{expect(r.request().headers().authorization).toBe('Bearer test-access-token');return r.fulfill({body:'A cloud book, imported only after selection.',contentType:'text/plain'});});
 await page.goto('/mobile/');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Connect cloud storage',exact:true}).click();expect(sdk).toEqual([]);
 await page.getByRole('button',{name:'Connect OneDrive',exact:true}).click();await expect(page.locator('.cloud-backup')).toContainText('Add a Microsoft Application Client ID');
 await page.getByLabel('Google OAuth Client ID').fill('test.apps.googleusercontent.com');await page.getByLabel('Google API key').fill('restricted-public-key');await page.getByLabel('Google Cloud project number').fill('123456');await page.getByRole('button',{name:'Save connection settings',exact:true}).click();await page.getByRole('button',{name:'Connect Google Drive',exact:true}).click();await expect.poll(()=>sdk.length).toBe(2);
 await page.getByRole('button',{name:'Choose Google Drive file',exact:true}).click();await expect(page.locator('.cloud-backup')).toContainText('Book added to your shelf.');expect(await page.evaluate(()=>testScope)).toBe('https://www.googleapis.com/auth/drive.file');expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('test-access-token');
 await page.getByRole('button',{name:'Shelf',exact:true}).click();await expect(page.locator('#shelf .book')).toHaveCount(1);
});
test('personal OneDrive uses PKCE, rejects wrong-state callbacks and imports selected files without persisting tokens',async({page,context})=>{

 await context.route('https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize**',r=>r.fulfill({contentType:'text/html',body:'<p>Mock consent</p>'}));
 await context.route('https://login.microsoftonline.com/consumers/oauth2/v2.0/token',r=>{const body=new URLSearchParams(r.request().postData());expect(body.get('code_verifier').length).toBeGreaterThanOrEqual(43);expect(body.get('grant_type')).toBe('authorization_code');return r.fulfill({json:{access_token:'microsoft-test-token'}});});
 await context.route('https://graph.microsoft.com/v1.0/me/drive/root/children**',r=>{expect(r.request().headers().authorization).toBe('Bearer microsoft-test-token');return r.fulfill({json:{value:[{id:'chosen',name:'OneDrive book.txt',size:40,file:{},'@microsoft.graph.downloadUrl':'https://books.files.1drv.com/chosen'}]}});});
 await context.route('https://books.files.1drv.com/chosen',r=>{expect(r.request().headers().authorization).toBeUndefined();return r.fulfill({body:'A selected OneDrive book.',contentType:'text/plain'});});
 await page.goto('/mobile/');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Connect cloud storage',exact:true}).click();await page.getByLabel('Microsoft Application Client ID').fill('12345678-1234-1234-1234-123456789abc');await page.getByRole('button',{name:'Save connection settings',exact:true}).click();
 const popupReady=page.waitForEvent('popup');await page.getByRole('button',{name:'Connect OneDrive',exact:true}).click();const popup=await popupReady;await expect.poll(()=>popup.url()).toContain('code_challenge=');const url=new URL(popup.url());expect(url.searchParams.get('code_challenge_method')).toBe('S256');const state=url.searchParams.get('state'),redirect=url.searchParams.get('redirect_uri');
 await page.evaluate(()=>window.postMessage({type:'sela:cloud-auth',state:'wrong',code:'fake'},location.origin));await expect(page.locator('.cloud-files')).toBeEmpty();
 await popup.goto(redirect+'?code=mock-code&state='+encodeURIComponent(state)).catch(e=>{if(!/closed/.test(e.message))throw e;});await expect(page.locator('.cloud-files')).toContainText('OneDrive book.txt');await page.getByRole('button',{name:'OneDrive book.txt',exact:true}).click();await expect(page.locator('.cloud-backup')).toContainText('Book added to your shelf.');expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('microsoft-test-token');await page.getByRole('button',{name:'Disconnect',exact:true}).click();await expect(page.locator('.cloud-files')).toBeEmpty();
});
test('shared interface has working previews, direct theme control and embeds below the playground',async({page})=>{
 await page.goto('/?geo=off');await page.locator('.trial-book').click();const reader=page.locator('[data-product-reader=app]');await expect(reader.locator('.library-reader-header,.library-reader-footer')).toHaveCount(0);
 await reader.getByRole('button',{name:'Appearance: auto',exact:true}).click();await expect(reader).toHaveAttribute('data-flippy-theme','light');await reader.getByRole('button',{name:'Appearance: light',exact:true}).click();await expect(reader).toHaveAttribute('data-flippy-theme','dark');
 await reader.getByRole('button',{name:'Page previews',exact:true}).click();await expect(reader.locator('.library-reader-thumb')).toHaveCount(50);await reader.getByRole('button',{name:'Preview page 4',exact:true}).click();await expect(reader.locator('.app-page-previews')).toBeHidden();await expect(reader).not.toHaveClass(/app-panel-open/);await expect(reader.locator('.library-reader-page-form input')).toHaveValue('4');
 await reader.getByRole('button',{name:'Back to library',exact:true}).click();await page.locator('.developer-playground').evaluate(e=>e.open=true);await page.locator('#demo-presentation').selectOption('inline');await page.locator('.launch-reader').click();await expect(page.locator('#embedded-reader .app-reading-top')).toBeVisible();const positions=await page.evaluate(()=>({embed:document.getElementById('embedded-reader').getBoundingClientRect().top,control:document.getElementById('demo-presentation').getBoundingClientRect().bottom}));expect(positions.embed).toBeGreaterThan(positions.control);
});
