import {test,expect} from '@playwright/test';
const android='Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/130.0 Mobile Safari/537.36';
test('iPad desktop-style signals open mobile Bookshelf',async({browser})=>{
 const context=await browser.newContext({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 Version/17.0 Safari/605.1.15'});await context.addInitScript(()=>Object.defineProperty(navigator,'maxTouchPoints',{get:()=>5}));const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');await expect(page.locator('[data-i18n=title]')).toHaveText('Your books. Within reach.');await context.close();
});
test('blocked browser storage shows a basic mobile fallback',async({browser})=>{
 const context=await browser.newContext({userAgent:android});await context.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('Storage blocked');};});const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#device-notice')).toContainText('could not initialize');await expect(page.locator('#legacy-mobile')).toBeVisible();await context.close();
});
test('public three-product routing and desktop mobile-app notice',async({page})=>{
 await page.goto('/?geo=off');await expect(page.locator('#products article')).toHaveCount(3);await page.locator('#get-bookshelf').click();await expect(page.locator('#product-status')).toContainText('phones/tablets');expect(new URL(page.url()).pathname).toBe('/');
 await page.goto('/mobile/');await expect(page.locator('#device-notice')).toContainText('phones and tablets');await expect(page.locator('#mobile-app')).toBeHidden();expect(await page.locator('#mobile-manifest').getAttribute('href')).toBeNull();
});
test('mobile route blocks Home installation and provides basic old-browser fallback',async({browser})=>{
 const context=await browser.newContext({userAgent:android,viewport:{width:320,height:740}});const page=await context.newPage();await page.goto('/?geo=off');await page.locator('#get-home').click();await expect(page.locator('#product-status')).toContainText('desktop');
 await page.goto('/extension/library.html');await expect(page.locator('#home-device-notice')).toBeVisible();await expect(page.locator('#home-app')).toBeHidden();
 await page.addInitScript(()=>{window.ResizeObserver=undefined;});await page.goto('/mobile/');await expect(page.locator('#legacy-mobile')).toBeVisible();await expect(page.locator('#mobile-app')).toBeHidden();await context.close();
});
test('mobile bookshelf filters, favorites, views, bottom navigation and five examples',async({browser})=>{
 const context=await browser.newContext({userAgent:android,viewport:{width:320,height:740},serviceWorkers:'block'});const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toBeVisible();await expect(page.locator('.sample-covers article')).toHaveCount(5);
 await page.locator('#books').setInputFiles([{name:'First.txt',mimeType:'text/plain',buffer:Buffer.from('First mobile book')},{name:'Second.md',mimeType:'text/markdown',buffer:Buffer.from('# Second mobile book')}]);await expect(page.locator('.book')).toHaveCount(2);await expect(page.locator('#books')).toBeEnabled();await page.locator('#format-filter').selectOption('md');await expect(page.locator('.book')).toHaveCount(1);await page.getByRole('button',{name:'Book options: Second',exact:true}).click();await page.getByRole('button',{name:'Favorite',exact:true}).click();await page.locator('#format-filter').selectOption('all');await page.locator('#read-filter').selectOption('favorite');await expect(page.locator('.book')).toHaveCount(1);
 await page.locator('#shelf-view').click();await page.locator('#shelf-view').click();await expect(page.locator('body')).toHaveAttribute('data-shelf-view','list');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('[data-tab=continue]').click();await expect(page.locator('.flippy-epub article')).toBeVisible();await page.keyboard.press('Escape');await page.locator('[data-tab=settings]').click();await expect(page.locator('.library-info')).toHaveAttribute('open','');await page.reload();await expect(page.locator('.book')).toHaveCount(2);await expect(page.locator('body')).toHaveAttribute('data-shelf-view','list');await context.close();
});
test('Home quotes work offline and city weather is opt-in with attribution',async({page})=>{
 const requests=[];page.on('request',r=>{if(r.url().includes('open-meteo'))requests.push(r.url());});await page.route('https://geocoding-api.open-meteo.com/**',r=>r.fulfill({json:{results:[{name:'Jakarta',country:'Indonesia',latitude:-6.2,longitude:106.8}]}}));await page.route('https://api.open-meteo.com/**',r=>r.fulfill({json:{current:{temperature_2m:29,weather_code:0}}}));await page.goto('/extension/library.html');await expect(page.locator('#daily-quote')).not.toBeEmpty();const quote=await page.locator('#daily-quote').textContent();await page.locator('#new-quote').click();expect(await page.locator('#daily-quote').textContent()).not.toBe(quote);expect(requests).toEqual([]);await page.locator('#weather-city').fill('Jakarta');await page.locator('#weather-form button').click();await expect(page.locator('#weather-status')).toContainText('29 °C');expect(requests).toHaveLength(2);await page.locator('#weather-clear').click();expect(await page.evaluate(()=>localStorage.getItem('sela-home:weather'))).toBeNull();
});
