import {test,expect} from '@playwright/test';
const android='Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/130.0 Mobile Safari/537.36';
test('iPad desktop-style signals open mobile Bookshelf',async({browser})=>{
 const context=await browser.newContext({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 Version/17.0 Safari/605.1.15'});await context.addInitScript(()=>Object.defineProperty(navigator,'maxTouchPoints',{get:()=>5}));const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');await expect(page.locator('[data-i18n=title]')).toHaveText('Your books.');await context.close();
});
test('blocked browser storage shows a basic mobile fallback',async({browser})=>{
 const context=await browser.newContext({userAgent:android});await context.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('Storage blocked');};});const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#device-notice')).toContainText('could not initialize');await expect(page.locator('#legacy-mobile')).toBeVisible();await context.close();
});
test('two products and installable Reader on desktop',async({page})=>{
 await page.goto('/?geo=off');await expect(page.locator('#products article')).toHaveCount(2);await expect(page.locator('#get-home')).toHaveCount(0);await page.locator('#get-bookshelf').click();await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');await expect(page.locator('#device-notice')).toBeHidden();expect(await page.locator('#mobile-manifest').getAttribute('href')).toBe('manifest.webmanifest');
 for(const width of [320,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.locator('[data-tab=settings]').click();await expect(page.locator('#install-mobile-app')).toBeVisible();await page.locator('#install-mobile-app').click();await expect(page.locator('#mobile-offline-status')).toContainText('Install app');
});
test('old-browser fallback remains available without OS restrictions',async({browser})=>{
 const context=await browser.newContext({userAgent:android,viewport:{width:320,height:740}});await context.addInitScript(()=>{window.ResizeObserver=undefined;});const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#legacy-mobile')).toBeVisible();await expect(page.locator('#mobile-app')).toBeHidden();await context.close();
});

test('mobile bookshelf filters, favorites, views, bottom navigation and separate sample catalog',async({browser})=>{
 const context=await browser.newContext({userAgent:android,viewport:{width:320,height:740},serviceWorkers:'block'});const page=await context.newPage();await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toBeVisible();await expect(page.locator('.home-page .catalog-book')).toHaveCount(1);await page.locator('[data-tab=library]').click();await expect(page.locator('#empty img')).toHaveCount(0);
 await page.locator('#books').setInputFiles([{name:'First.txt',mimeType:'text/plain',buffer:Buffer.from('First mobile book')},{name:'Second.md',mimeType:'text/markdown',buffer:Buffer.from('# Second mobile book')}]);await expect(page.locator('.book')).toHaveCount(2);await expect(page.locator('#books')).toBeEnabled();await page.locator('#format-filter').selectOption('md');await expect(page.locator('.book')).toHaveCount(1);await page.getByRole('button',{name:'Book options: Second',exact:true}).click();await page.locator('.book-actions').getByRole('button',{name:'Favorite',exact:true}).click();await page.locator('#format-filter').selectOption('all');await page.locator('#read-filter').selectOption('favorite');await expect(page.locator('.book')).toHaveCount(1);
 await page.locator('#shelf-view').click();await page.locator('#shelf-view').click();await expect(page.locator('body')).toHaveAttribute('data-shelf-view','list');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.cover').click();await expect(page.locator('.flippy-epub article')).toBeVisible();await page.keyboard.press('Escape');await page.locator('[data-tab=settings]').click();await expect(page.locator('.settings-page')).toBeVisible();await page.locator('.library-info summary').click();await expect(page.locator('.library-info')).toHaveAttribute('open','');await page.reload();await expect(page.locator('.book')).toHaveCount(2);await expect(page.locator('body')).toHaveAttribute('data-shelf-view','list');await context.close();
});
test('Reader clock and coffee pause work without third-party requests',async({page})=>{
 const requests=[];page.on('request',r=>{if(r.url().includes('open-meteo'))requests.push(r.url());});await page.setViewportSize({width:1440,height:900});await page.goto('/mobile/');await expect(page.locator('#clock')).not.toHaveText('--:--');await page.locator('#coffee').click();await expect(page.locator('#status')).toContainText('A small pause');expect(requests).toEqual([]);
});
