import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';

test('CDN app interface is loaded on open, works inline, and keeps palettes inside its host',async({page})=>{
 const requested=[];page.on('request',r=>requested.push(r.url()));await page.goto('/?geo=off');
 expect(requested.some(url=>url.endsWith('/sela.app.js'))).toBe(false);
 await page.evaluate(async()=>{await SelaReady;const host=document.createElement('div');host.id='app-demo-host';host.style.height='560px';document.body.append(host);window.demoReader=new Sela({url:'/example/yang-tidak-ikut-pulang.pdf',presentation:'inline',container:host,ui:'app',mode:'single',language:'en',metadata:{author:'Bobby Fajar Christian',year:'2026'},theme:'light'});await demoReader.open();});
 const app=page.locator('#app-demo-host [data-product-reader=app]');await app.scrollIntoViewIfNeeded();await expect(app.locator('.app-reading-top')).toBeVisible();
 expect((await app.locator('.library-reader-shell').boundingBox()).height).toBeLessThanOrEqual(560);
 await app.getByRole('button',{name:'Reader settings',exact:true}).click();await app.getByRole('button',{name:'Seroja',exact:true}).click();await expect(app).toHaveAttribute('data-palette','rose');expect(await page.locator('html').getAttribute('data-palette')).toBeNull();
 await app.getByRole('button',{name:'Book information',exact:true}).click();await expect(app.locator('.app-info-panel')).toContainText('Bobby Fajar Christian');await expect(app.locator('.app-info-panel')).toContainText('2026');await page.keyboard.press('Escape');
 await app.getByRole('button',{name:'Bookmark page',exact:true}).click();await app.getByRole('button',{name:'Contents & bookmarks',exact:true}).click();await expect(app.getByRole('button',{name:'Bookmarked page 1',exact:true})).toBeVisible();await expect(app.locator('.sela-tools-top button')).toHaveCount(1);await expect(app.locator('.app-tools-close')).toHaveCount(0);
 await app.getByRole('button',{name:'Bookmark page',exact:true}).click();await expect(app.getByRole('button',{name:'Bookmarked page 1',exact:true})).toHaveCount(0);await expect(app.locator('.app-saved-marks')).toContainText('Tap the bookmark icon');await app.getByRole('button',{name:'Bookmark page',exact:true}).focus();await page.keyboard.press('b');await expect(app.getByRole('button',{name:'Bookmarked page 1',exact:true})).toBeVisible();
 await app.getByRole('button',{name:'Close tools',exact:true}).click();await page.evaluate(()=>demoReader.destroy());await expect(app).toHaveCount(0);
});

test('reading cards export actual PNGs for a quote and the current PDF page',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Read sample',exact:true}).click();const app=page.locator('[data-product-reader=app]');
 await app.getByRole('button',{name:'Screenshot & quote',exact:true}).click();const panel=app.locator('.app-share-panel');await panel.getByLabel('Quote text').fill('Ada yang tetap tinggal, bahkan sesudah kita pulang.');await panel.getByRole('button',{name:'Create preview',exact:true}).click();await expect(panel.locator('img')).toBeVisible();
 const pixels=await panel.locator('img').evaluate(async img=>{await img.decode();return [img.naturalWidth,img.naturalHeight];});expect(pixels).toEqual([1080,1350]);
 const downloaded=page.waitForEvent('download');await panel.getByRole('button',{name:'Download PNG',exact:true}).click();const bytes=await readFile(await(await downloaded).path());expect(bytes.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false});});await panel.getByRole('button',{name:'Share image',exact:true}).click();await expect(panel.getByRole('status')).toContainText('Download PNG');
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.sharedCard={name:data.files[0].name,type:data.files[0].type,size:data.files[0].size};}});});await panel.getByRole('button',{name:'Share image',exact:true}).click();const shared=await page.evaluate(()=>window.sharedCard);expect(shared.name).toBe('sela-reading-card.png');expect(shared.type).toBe('image/png');expect(shared.size).toBeGreaterThan(1000);
 await panel.getByLabel('Card type').selectOption('page');await panel.getByRole('button',{name:'Create preview',exact:true}).click();await expect(panel.getByRole('button',{name:'Download PNG',exact:true})).toBeEnabled();await expect(panel.locator('img')).toBeVisible();await page.keyboard.press('Escape');await expect(panel).toBeHidden();await app.getByRole('button',{name:'Back to library',exact:true}).click();expect(errors).toEqual([]);
});

test('library book info is editable, safely rendered and retained by full backup',async({page})=>{
 await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');await page.locator('#books').setInputFiles({name:'Letters.html',mimeType:'text/html',buffer:Buffer.from('<html lang="id"><head><title>Letters</title><meta name="author" content="A Writer"><meta name="description" content="A quiet book"></head><body><p>A letter.</p></body></html>')});await page.locator('[data-tab=library]').click();await expect(page.locator('.book')).toHaveCount(1);
 await page.getByRole('button',{name:'Read Letters',exact:true}).click();await expect(page.locator('.app-reading-top')).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Book information: Letters',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Book information'});await expect(dialog).toContainText('A Writer');await dialog.getByRole('button',{name:'Edit information',exact:true}).click();await dialog.getByLabel('Publication year',{exact:true}).fill('2024');await dialog.getByLabel('Description',{exact:true}).fill('<script>alert(1)</script> My own description');await dialog.getByRole('button',{name:'Save information',exact:true}).click();await expect(dialog).toHaveCount(0);
 const restored=await page.evaluate(async()=>{const {exportLibrary,restoreLibrary}=await import('/library/backup.js');const {listBooks,writeBook}=await import('/library/storage.js');const blob=await exportLibrary();for(const book of await listBooks())await writeBook(book,null,true);await restoreLibrary(blob);return(await listBooks())[0].metadata;});expect(restored.author).toBe('A Writer');expect(restored.year).toBe('2024');expect(restored.description).toContain('<script>');await page.reload();await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');await page.locator('[data-tab=library]').click();await page.getByRole('button',{name:'Book information: Letters',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('My own description');expect(await page.getByRole('dialog').locator('script').count()).toBe(0);
});

test('public portrait covers and compact app home remain balanced across themes and sizes',async({page})=>{
 await page.goto('/?geo=off');await expect(page.locator('.developer-playground')).not.toHaveAttribute('open','');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const theme of ['light','dark']){await page.locator('[data-theme-choice='+theme+']').click();const box=await page.locator('.trial-cover').boundingBox();expect(Math.abs(box.width/box.height-2/3)).toBeLessThan(.01);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}
 await page.setViewportSize({width:1440,height:900});await page.screenshot({path:(process.env.CI?'test-results/':'C:/Devs/_backups/sela-refresh-2026-10-10/')+'public-refresh.png',fullPage:true});await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});const actions=page.locator('.home-page .catalog-actions');const first=await actions.locator('button').nth(0).boundingBox(),second=await actions.locator('button').nth(1).boundingBox();expect(Math.abs(first.y-second.y)).toBeLessThan(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.screenshot({path:(process.env.CI?'test-results/':'C:/Devs/_backups/sela-refresh-2026-10-10/')+'home-refresh.png',fullPage:true});await page.setViewportSize({width:390,height:852});await page.screenshot({path:(process.env.CI?'test-results/':'C:/Devs/_backups/sela-refresh-2026-10-10/')+'home-refresh-phone.png',fullPage:true});
});

test('publishing metadata uses EPUB/DC fields, comic metadata and never mistakes PDF creation for release year',async({page})=>{
 await page.goto('/?geo=off');const result=await page.evaluate(async()=>{const {epubMetadata,comicMetadata,readBookMetadata}=await import('/dist/js/sela.metadata.js');const parse=xml=>new DOMParser().parseFromString(xml,'application/xml');return {epub:epubMetadata(parse('<package><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>Book</dc:title><dc:creator>A Writer</dc:creator><dc:date>2020-03-12</dc:date><dc:language>id</dc:language><dc:publisher>Press</dc:publisher><dc:identifier>urn:isbn:9781234567890</dc:identifier><dc:description>&lt;b&gt;A story&lt;/b&gt;&lt;script&gt;window.bad=1&lt;/script&gt;</dc:description></metadata></package>')),comic:comicMetadata(parse('<ComicInfo><Title>A Comic</Title><Writer>Writer</Writer><Year>2019</Year><Series>Series</Series></ComicInfo>')),pdf:await readBookMetadata({numPages:3,pdf:{getMetadata:async()=>({info:{Title:'PDF',CreationDate:'D:20241010'}})}})};});expect(result.epub).toMatchObject({title:'Book',author:'A Writer',year:'2020',language:'id',publisher:'Press',isbn:'9781234567890',description:'A story'});expect(result.comic).toMatchObject({title:'A Comic',year:'2019',series:'Series'});expect(result.pdf.year).toBeUndefined();expect(result.pdf.pageCount).toBe(3);
});
