import {test,expect} from '@playwright/test';
test('classic collection searches locally, shows covers and reads imported books within Sela',async({page})=>{
 const network=[];page.on('request',r=>{if(/openlibrary|gutendex|googleapis|microsoftonline|raw.githubusercontent/.test(r.url()))network.push(r.url());});
 await page.route('https://raw.githubusercontent.com/GITenberg/**',r=>r.fulfill({contentType:'text/plain',body:'Chapter One\n\nA complete classic stays inside Sela.\n\nChapter Two\n\nThe story continues.'}));
 await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');expect(network).toEqual([]);
 await page.getByRole('button',{name:'Explore',exact:true}).click();await page.getByRole('button',{name:'Find open books',exact:true}).click();const catalog=page.locator('.open-catalog');await expect(catalog.locator('.open-book')).toHaveCount(8);expect(network).toEqual([]);await expect(catalog.locator('a')).toHaveCount(0);
 await catalog.getByRole('searchbox').fill('Austen');await expect(catalog.locator('.open-book')).toHaveCount(1);await expect(catalog.locator('.open-book img')).toBeVisible();await catalog.getByRole('button',{name:'Read',exact:true}).click();await expect(page.locator('.flippy-epub article')).toContainText('A complete classic stays inside Sela.');await expect(page.locator('.flippy-epub article h2')).toHaveCount(2);await page.getByRole('button',{name:'Back to library',exact:true}).click();
 await page.getByRole('button',{name:'Shelf',exact:true}).click();await expect(page.locator('#shelf .book')).toHaveCount(1);await expect(page.locator('#shelf .book img')).toBeVisible();await page.getByRole('button',{name:'Home',exact:true}).click();await expect(page.locator('.continue-list .recent-book')).toHaveCount(1);await expect(page.locator('.reading-summary strong').first()).toHaveText('1');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.locator('input[placeholder*=Client],#connect-cloud')).toHaveCount(0);await page.locator('#language').click();await page.getByRole('button',{name:'Jelajah',exact:true}).click();await expect(catalog.getByRole('button',{name:'Baca',exact:true})).toBeVisible();
});
test('failed book download stays inside the collection and does not invent shelf success',async({page})=>{
 await page.route('https://raw.githubusercontent.com/GITenberg/**',r=>r.fulfill({status:503,body:'Unavailable'}));await page.goto('/mobile/');await page.getByRole('button',{name:'Explore',exact:true}).click();await page.getByRole('button',{name:'Find open books',exact:true}).click();const catalog=page.locator('.open-catalog');await catalog.getByRole('searchbox').fill('Frankenstein');await catalog.getByRole('button',{name:'Save offline',exact:true}).click();await expect(catalog).toContainText('Could not load this book');await expect(catalog.getByRole('button',{name:'Save offline',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Shelf',exact:true}).click();await expect(page.locator('#shelf .book')).toHaveCount(0);
});
test('home has one import control, balanced cards, timer and opt-in city weather',async({page})=>{
 const requests=[];page.on('request',r=>{if(/open-meteo/.test(r.url()))requests.push(r.url());});await page.route('https://geocoding-api.open-meteo.com/**',r=>r.fulfill({json:{results:[{name:'Yogyakarta',admin1:'DIY',country:'Indonesia',latitude:-7.8,longitude:110.36}]}}));await page.route('https://api.open-meteo.com/**',r=>r.fulfill({json:{current:{temperature_2m:27.4,weather_code:3}}}));
 await page.goto('/mobile/');await expect(page.locator('#mobile-app')).toHaveAttribute('data-ready','true');expect(requests).toEqual([]);await expect(page.locator('.home-page .continue-section')).toBeHidden();await expect(page.locator('.topbar #add-books')).toHaveCount(1);await expect(page.locator('.home-page button').filter({hasText:'Add a book'})).toHaveCount(0);
 await page.getByText('Choose city',{exact:true}).click();await page.getByRole('searchbox',{name:'City name'}).fill('Jogja');await page.getByRole('button',{name:'Find',exact:true}).click();await page.getByRole('button',{name:'Yogyakarta, DIY, Indonesia',exact:true}).click();await expect(page.locator('.weather-summary strong')).toHaveText('27°C');await expect(page.locator('.weather-summary span')).toHaveText('Cloudy');
 const focus=page.locator('.focus-card');await focus.getByRole('button',{name:'Start',exact:true}).click();await expect(focus.getByRole('button',{name:'Pause',exact:true})).toBeVisible();await focus.getByRole('button',{name:'Pause',exact:true}).click();await focus.getByRole('combobox').selectOption('25');await expect(focus.locator('output')).toHaveText('25:00');await focus.getByRole('button',{name:'Reset',exact:true}).click();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const colorScheme of ['light','dark']){await page.emulateMedia({colorScheme});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}if(width>=800){const book=await page.locator('.home-page .catalog-book').boundingBox(),timer=await focus.boundingBox();expect(Math.abs(book.y-timer.y)).toBeLessThan(3);expect(Math.abs(book.height-timer.height)).toBeLessThan(3);}}
 await page.reload();await expect(page.locator('.weather-summary strong')).toHaveText('27°C');expect(requests).toHaveLength(2);await page.getByText('Yogyakarta, DIY, Indonesia',{exact:true}).click();await page.getByRole('button',{name:'Turn off weather',exact:true}).click();await expect(page.locator('.weather-summary strong')).toHaveText('—');
});
